#!/bin/bash

sf="`pwd`/env/safeexec"

if [ "$1" == "" -o "$2" == "" -o "$3" == "" ]; then
    exit 43
fi
if [ ! -x "$1" ]; then
    exit 44
fi
if [ ! -r "$2" ]; then
    exit 45
fi
if [ ! -x $sf ]; then
    exit 46
fi

time=$3
if [ "$time" -gt "0" ]; then
  let "ttime = $time + 30"
else
  time=1
  ttime=30
fi

nruns=1
if [ "$4" != "" ]; then
  if [ "$4" -gt "0" ]; then
    nruns=$4
  fi
fi
maxm=512000
if [ "$5" != "" ]; then
  if [ "$5" -gt "0" ]; then
    maxm=${5}000
  fi
fi
maxf=1024
if [ "$6" != "" ]; then
  if [ "$6" -gt "0" ]; then
    maxf=${6}
  fi
fi

cp "$2" stdin0 2> /dev/null
cp "$1" run.exe 2> /dev/null

file run.exe | grep -iq "statically linked"
if [ "$?" != "0" ]; then
  exit 47
fi

bocau=`id -u`
bocag=`id -g`

cdir=`pwd`

$sf -F10 -f$maxf -r$nruns -n0 -R$cdir -C. -U$bocau -G$bocag -K -ostdout0 -estderr0 -d$maxm -m$maxm -t$time -T$ttime -istdin0 ./run.exe
ret=$?
if [ $ret -gt 10 ]; then
	ret=0
fi


#  compare/c src/output2 stdout0

exit $ret
