#!/bin/bash
# ////////////////////////////////////////////////////////////////////////////////
# //BOCA Online Contest Administrator
# //    Copyright (C) 2003-2012 by BOCA System (bocasystem@gmail.com)
# //
# //    This program is free software: you can redistribute it and/or modify
# //    it under the terms of the GNU General Public License as published by
# //    the Free Software Foundation, either version 3 of the License, or
# //    (at your option) any later version.
# //
# //    This program is distributed in the hope that it will be useful,
# //    but WITHOUT ANY WARRANTY; without even the implied warranty of
# //    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# //    GNU General Public License for more details.
# //    You should have received a copy of the GNU General Public License
# //    along with this program.  If not, see <http://www.gnu.org/licenses/>.
# ////////////////////////////////////////////////////////////////////////////////
#Last modified: 21/july/2012 by cassio@ime.usp.br
#
# parameters are:
# $1 source_file
# $2 exe_file (default run.jar)
# $3 timelimit (optional, limit to run all the repetitions, by default only one repetition)
# $4 maximum allowed memory (in MBytes)
#
# the output of the submission should be directed to the standard output
#
# the return code show what happened (according to safeexec):
# 0 ok
# 1 compile error
# 2 runtime error
# 3 timelimit exceeded
# 4 internal error
# 5 parameter error
# 6 internal error
# 7 memory limit exceeded
# 8 security threat
# 9 runtime error
# other_codes are unknown to boca: in this case BOCA will present the
#                                  last line of standard output to the judge

if [ "$1" == "" ]; then
    echo "parameter problem"
    exit 43
fi
name="$1"
if [ ! -r "$1" ]; then

  ttime=30
fi
maxm=512
if [ "$4" != "" -a "$4" -gt "0" ]; then
  maxm=$4
fi

if [ "$2" == "" ]; then
  jarfile=run.jar
else
  jarfile=$2
fi

cdir=`pwd`
echo "Current directory is $cdir" >&2

cp $name .

name=`echo $name | cut -d'/' -f2`
mainname=`echo $name | cut -d'.' -f1`
if [ "$mainname" == "" ]; then
  mainname=Main
fi

#find . -name "*.java" | while read lin; do
#  \$javac "\$lin"
#  echo \$? > ../compileit.retcode
#done

echo "COMPILATION IS NOT BEING CHROOTED -- THIS IS NOT AN IDEAL SETTING"
/bin/javac $name 2> log
ret=$?

if [ "$ret" != "0" ]; then
  echo "Compilation Error: $ret"
  exit $ret
fi

rm -f ./run.jar
/bin/jar cvfe ./$jarfile $mainname "$mainname.class"

#$sf -r1 -t$time -T$ttime -F256 -u256 -U$bocau -G$bocag -ostdout0 -estderr0 -n0 -C. -d20000000 -m20000000 ./compileit.sh

if [ -f "stdout0" ]; then
	cat "stdout0"
fi
if [ -f "stderr0" ]; then
	cat "stderr0"
fi

exit $ret
