#!/bin/bash

if [ "$1" == "" ]; then
    exit 43
fi
if [ ! -r "$1" ]; then
    exit 44
fi
name="$1"
if [ ! -r "$1" ]; then
    exit 44
fi

maxm=512000
if [ "$4" != "" ]; then
  if [ "$4" -gt "0" ]; then
    maxm=${4}000
  fi
fi

# setting up the timelimit according to the problem
if [ "$3" == "" ]; then
  time=5
else
  time=$3
fi
let "ttime = $time + 30"

if [ "$2" == "" ]; then
  exe=run.exe
else
  exe=$2
fi

rm -f $exe compileit.retcode runit.retcode stderr0  stdin0  stdout0 2> /dev/null

cdir=`pwd`
/usr/bin/gcc -Wall -static -O2 -o $exe $name -lm 2> log
ret=$?

exit $ret
